export * from './student-dashboard/student-dashboard.component'
export * from './student-form/student-form.component'
export * from './student-form/student-form.form'
export * from './student-login-form/student-login-form.component'
export * from './student-profile/student-profile.component'
export * from './student-table/student-table.component'
